on:
  release:
    types: [ published ]

jobs:
  build:
    name: publish release on MavenCentral

    runs-on: macos-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: MavenCentral upload
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSS_SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
        run: |
          ./gradlew publish --no-daemon --no-parallel
          ./gradlew closeAndReleaseRepository